#ifndef _HDRTAB_H
#define _HDRTAB_H


static wchar_t* headerTabCharacteristicsNames[] =
{
	L"IMAGE_FILE_RELOCS_STRIPPED",
	L"IMAGE_FILE_EXECUTABLE_IMAGE",
	L"IMAGE_FILE_LINE_NUMS_STRIPPED",
	L"IMAGE_FILE_LOCAL_SYMS_STRIPPED",
	L"IMAGE_FILE_AGGRESIVE_WS_TRIM",
	L"IMAGE_FILE_LARGE_ADDRESS_AWARE",
	L"IMAGE_FILE_BYTES_REVERSED_LO",
	L"IMAGE_FILE_32BIT_MACHINE",
	L"IMAGE_FILE_DEBUG_STRIPPED",
	L"IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP",
	L"IMAGE_FILE_NET_RUN_FROM_SWAP",
	L"IMAGE_FILE_SYSTEM",
	L"IMAGE_FILE_DLL",
	L"IMAGE_FILE_UP_SYSTEM_ONLY",
	L"IMAGE_FILE_BYTES_REVERSED_HI"
};

static int headerTabCharacteristicsValues[] =
{
	0x0001,
	0x0002,
	0x0004,
	0x0008,
	0x0010,
	0x0020,
	0x0080,
	0x0100,
	0x0200,
	0x0400,
	0x0800,
	0x1000,
	0x2000,
	0x4000,
	0x8000
};

static wchar_t* headerTabSectionDllCharacteristicFlagNames[] =
{
	L"IMAGE_LIBRARY_PROCESS_INIT",
	L"IMAGE_LIBRARY_PROCESS_TERM",
	L"IMAGE_LIBRARY_THREAD_INIT",
	L"IMAGE_LIBRARY_THREAD_TERM",
	L"IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA",
	L"IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE",
	L"IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY",
	L"IMAGE_DLLCHARACTERISTICS_NX_COMPAT",
	L"IMAGE_DLLCHARACTERISTICS_NO_ISOLATION",
	L"IMAGE_DLLCHARACTERISTICS_NO_SEH",
	L"IMAGE_DLLCHARACTERISTICS_NO_BIND",
	L"IMAGE_DLLCHARACTERISTICS_APPCONTAINER",
	L"IMAGE_DLLCHARACTERISTICS_WDM_DRIVER",
	L"IMAGE_DLLCHARACTERISTICS_GUARD_CF",
	L"IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE"
};

static wchar_t* headerTabMachineNames[] =
{
	L"IMAGE_FILE_MACHINE_UNKNOWN",
	L"IMAGE_FILE_MACHINE_TARGET_HOST",
	L"IMAGE_FILE_MACHINE_I386",
	L"IMAGE_FILE_MACHINE_R3000",
	L"IMAGE_FILE_MACHINE_R4000",
	L"IMAGE_FILE_MACHINE_R10000",
	L"IMAGE_FILE_MACHINE_WCEMIPSV2",
	L"IMAGE_FILE_MACHINE_ALPHA",
	L"IMAGE_FILE_MACHINE_SH3",
	L"IMAGE_FILE_MACHINE_SH3DSP",
	L"IMAGE_FILE_MACHINE_SH3E",
	L"IMAGE_FILE_MACHINE_SH4",
	L"IMAGE_FILE_MACHINE_SH5",
	L"IMAGE_FILE_MACHINE_ARM",
	L"IMAGE_FILE_MACHINE_THUMB",
	L"IMAGE_FILE_MACHINE_ARMNT",
	L"IMAGE_FILE_MACHINE_AM33",
	L"IMAGE_FILE_MACHINE_POWERPC",
	L"IMAGE_FILE_MACHINE_POWERPCFP",
	L"IMAGE_FILE_MACHINE_IA64",
	L"IMAGE_FILE_MACHINE_MIPS16",
	L"IMAGE_FILE_MACHINE_ALPHA64",
	L"IMAGE_FILE_MACHINE_MIPSFPU",
	L"IMAGE_FILE_MACHINE_MIPSFPU16",
	L"IMAGE_FILE_MACHINE_AXP64",
	L"IMAGE_FILE_MACHINE_TRICORE",
	L"IMAGE_FILE_MACHINE_CEF",
	L"IMAGE_FILE_MACHINE_EBC",
	L"IMAGE_FILE_MACHINE_AMD64",
	L"IMAGE_FILE_MACHINE_M32R",
	L"IMAGE_FILE_MACHINE_ARM64",
	L"IMAGE_FILE_MACHINE_CEE",

	L"IMAGE_FILE_MACHINE_ARM64EC",
	L"IMAGE_FILE_MACHINE_ARM64X",
	L"IMAGE_FILE_MACHINE_R3000BE",
	L"IMAGE_FILE_MACHINE_RISCV32",
	L"IMAGE_FILE_MACHINE_RISCV64",
	L"IMAGE_FILE_MACHINE_RISCV128"
};

static int headerTabMachineValues[] =
{
	0,
	0x0001,
	0x014c,
	0x0162,
	0x0166,
	0x0168,
	0x0169,
	0x0184,
	0x01a2,
	0x01a3,
	0x01a4,
	0x01a6,
	0x01a8,
	0x01c0,
	0x01c2,
	0x01c4,
	0x01d3,
	0x01F0,
	0x01f1,
	0x0200,
	0x0266,
	0x0284,
	0x0366,
	0x0466,
	0x0284,
	0x0520,
	0x0CEF,
	0x0EBC,
	0x8664,
	0x9041,
	0xAA64,
	0xC0EE,

	0xA641,
	0xA64E,
	0x160,
	0x5032,
	0x5064,
	0x5128
};

static wchar_t* headerTabMagicNames[] =
{
	L"IMAGE_NT_OPTIONAL_HDR32_MAGIC",
	L"IMAGE_NT_OPTIONAL_HDR64_MAGIC",
	L"IMAGE_ROM_OPTIONAL_HDR_MAGIC"
};

static int headerTabMagicValues[] =
{
	0x010B,
	0x020B,
	0x0107
};

static wchar_t* headerTabSubsystemNames[] =
{
	L"IMAGE_SUBSYSTEM_UNKNOWN",
	L"IMAGE_SUBSYSTEM_NATIVE",
	L"IMAGE_SUBSYSTEM_WINDOWS_GUI",
	L"IMAGE_SUBSYSTEM_WINDOWS_CUI",
	L"IMAGE_SUBSYSTEM_OS2_GUI" // deprecated
	L"IMAGE_SUBSYSTEM_OS2_CUI",
	L"IMAGE_SUBSYSTEM_POSIX_GUI", // deprecated
	L"IMAGE_SUBSYSTEM_POSIX_CUI",
	L"IMAGE_SUBSYSTEM_NATIVE_WINDOWS",
	L"IMAGE_SUBSYSTEM_WINDOWS_CE_GUI",
	L"IMAGE_SUBSYSTEM_EFI_APPLICATION",
	L"IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER",
	L"IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER",
	L"IMAGE_SUBSYSTEM_EFI_ROM",
	L"IMAGE_SUBSYSTEM_XBOX",
	L"15", // unused
	L"IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION",
	L"IMAGE_SUBSYSTEM_XBOX_CODE_CATALOG"
};


static wchar_t* headerTabProperties[] =
{
	L"Signature",

	L"Machine",
	L"NumberOfSections",
	L"TimeDateStamp",
	L"PointerToSymbolTable",
	L"NumberOfSymbols",
	L"SizeOfOptionalHeader",
	L"Characteristics",

	L"Magic",
	L"MajorLinkerVersion",
	L"MinorLinkerVersion",
	L"SizeOfCode",
	L"SizeOfInitializedData",
	L"SizeOfUninitializedData",
	L"AddressOfEntryPoint",
	L"BaseOfCode",

	L"BaseOfData",


	L"ImageBase",
	L"SectionAlignment",
	L"FileAlignment",
	L"MajorOperatingSystemVersion",
	L"MinorOperatingSystemVersion",
	L"MajorImageVersion",
	L"MinorImageVersion",
	L"MajorSubsystemVersion",
	L"MinorSubsystemVersion",
	L"Win32VersionValue",
	L"SizeOfImage",
	L"SizeOfHeaders",
	L"CheckSum",
	L"Subsystem",
	L"DllCharacteristics",
	L"SizeOfStackReserve",
	L"SizeOfStackCommit",
	L"SizeOfHeapReserve",
	L"SizeOfHeapCommit",
	L"LoaderFlags",
	L"NumberOfRvaAndSizes",

	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_RESOURCE]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_EXCEPTION]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_SECURITY]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_BASERELOC]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_DEBUG]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_ARCHITECTURE]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_GLOBALPTR]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_TLS]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_IAT]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT]",
	L"DataDirectory[IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR]"
};

static wchar_t* headerTabSectionCharacteristicFlagNames[] =
{
	L"Reserved (0x00000001)",
	L"Reserved (0x00000002)",
	L"Reserved (0x00000004)",
	L"IMAGE_SCN_TYPE_NO_PAD (0x00000008)",
	L"Reserved (0x00000010)",
	L"IMAGE_SCN_CNT_CODE (0x00000020)",
	L"IMAGE_SCN_CNT_INITIALIZED_DATA (0x00000040)",
	L"IMAGE_SCN_CNT_UNINITIALIZED_DATA (0x00000080)",
	L"IMAGE_SCN_LNK_OTHER (0x00000100)",
	L"IMAGE_SCN_LNK_INFO (0x00000200)",
	L"Reserved (0x00000400)",
	L"IMAGE_SCN_LNK_REMOVE (0x00000800)",
	L"IMAGE_SCN_LNK_COMDAT (0x00001000)",
	L"Reserved (0x00002000)",
	L"IMAGE_SCN_NO_DEFER_SPEC_EXC (0x00004000)",
	L"IMAGE_SCN_GPREL (0x00008000)",
	L"Reserved (0x00010000)",
	L"IMAGE_SCN_MEM_PURGEABLE (0x00020000)",
	L"IMAGE_SCN_MEM_LOCKED (0x00040000)",
	L"IMAGE_SCN_MEM_PRELOAD (0x00080000)",
	L"IMAGE_SCN_ALIGN_1BYTES (0x00100000)",
	L"IMAGE_SCN_ALIGN_2BYTES (0x00200000)",
	L"IMAGE_SCN_ALIGN_4BYTES (0x00300000)", // -
	L"IMAGE_SCN_ALIGN_8BYTES (0x00400000)",
	L"IMAGE_SCN_ALIGN_16BYTES (0x00500000)",// -
	L"IMAGE_SCN_ALIGN_32BYTES (0x00600000)", // -
	L"IMAGE_SCN_ALIGN_64BYTES (0x00700000)", // -
	L"IMAGE_SCN_ALIGN_128BYTES (0x00800000)",
	L"IMAGE_SCN_ALIGN_256BYTES (0x00900000)",
	L"IMAGE_SCN_ALIGN_512BYTES (0x00A00000)",
	L"IMAGE_SCN_ALIGN_1024BYTES (0x00B00000)",
	L"IMAGE_SCN_ALIGN_2048BYTES (0x00C00000)",
	L"IMAGE_SCN_ALIGN_4096BYTES (0x00D00000)",
	L"IMAGE_SCN_ALIGN_8192BYTES (0x00E00000)",
	L"IMAGE_SCN_LNK_NRELOC_OVFL (0x01000000)",
	L"IMAGE_SCN_MEM_DISCARDABLE (0x02000000)",
	L"IMAGE_SCN_MEM_NOT_CACHED (0x04000000)",
	L"IMAGE_SCN_MEM_NOT_PAGED (0x08000000)",
	L"IMAGE_SCN_MEM_SHARED (0x10000000)",
	L"IMAGE_SCN_MEM_EXECUTE (0x20000000)",
	L"IMAGE_SCN_MEM_READ (0x40000000)",
	L"IMAGE_SCN_MEM_WRITE (0x80000000)"
};

static wchar_t* tabNames[] =
{
	L"Export",
	L"Import",
	L"Resource",
	L"Exception",
	L"Security",
	L"Base Relocation",
	L"Debug",
	L"Arch",
	L"Global Pointer",
	L"TLS",
	L"Load Config",
	L"Bound Import",
	L"IAT",
	L"Delay Import",
	L"COM Descriptor"
};

#endif /* _HDRTAB_H */